/*
JumpCloud API

Testing GSuiteImportApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jcapi2

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ConductorOne/baton-jumpcloud/pkg/jcapi2"
)

func Test_jcapi2_GSuiteImportApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GSuiteImportApiService GsuitesListImportJumpcloudUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gsuiteId string

		resp, httpRes, err := apiClient.GSuiteImportApi.GsuitesListImportJumpcloudUsers(context.Background(), gsuiteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GSuiteImportApiService GsuitesListImportUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gsuiteId string

		resp, httpRes, err := apiClient.GSuiteImportApi.GsuitesListImportUsers(context.Background(), gsuiteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
