/*
JumpCloud API

Testing CommandTriggersApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jcapi1

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/conductorone/baton-jumpcloud/pkg/jcapi1"
)

func Test_jcapi1_CommandTriggersApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CommandTriggersApiService CommandTriggerWebhookPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var triggername string

		resp, httpRes, err := apiClient.CommandTriggersApi.CommandTriggerWebhookPost(context.Background(), triggername).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
