/*
JumpCloud API

Testing FdeApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package github.com/ConductorOne/baton-jumpcloud/pkg/jcapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/github.com/ConductorOne/baton-jumpcloud/pkg/jcapi"
)

func Test_github.com/ConductorOne/baton-jumpcloud/pkg/jcapi_FdeApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FdeApiService SystemsGetFDEKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string

		resp, httpRes, err := apiClient.FdeApi.SystemsGetFDEKey(context.Background(), systemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
