/*
JumpCloud API

Testing SambaDomainsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package github.com/ConductorOne/baton-jumpcloud/pkg/jcapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/github.com/ConductorOne/baton-jumpcloud/pkg/jcapi"
)

func Test_github.com/ConductorOne/baton-jumpcloud/pkg/jcapi_SambaDomainsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SambaDomainsApiService LdapserversSambaDomainsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ldapserverId string
		var id string

		resp, httpRes, err := apiClient.SambaDomainsApi.LdapserversSambaDomainsDelete(context.Background(), ldapserverId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SambaDomainsApiService LdapserversSambaDomainsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ldapserverId string
		var id string

		resp, httpRes, err := apiClient.SambaDomainsApi.LdapserversSambaDomainsGet(context.Background(), ldapserverId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SambaDomainsApiService LdapserversSambaDomainsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ldapserverId string

		resp, httpRes, err := apiClient.SambaDomainsApi.LdapserversSambaDomainsList(context.Background(), ldapserverId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SambaDomainsApiService LdapserversSambaDomainsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ldapserverId string

		resp, httpRes, err := apiClient.SambaDomainsApi.LdapserversSambaDomainsPost(context.Background(), ldapserverId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SambaDomainsApiService LdapserversSambaDomainsPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ldapserverId string
		var id string

		resp, httpRes, err := apiClient.SambaDomainsApi.LdapserversSambaDomainsPut(context.Background(), ldapserverId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
