/*
JumpCloud API

Testing CloudInsightsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package github.com/ConductorOne/baton-jumpcloud/pkg/jcapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/github.com/ConductorOne/baton-jumpcloud/pkg/jcapi"
)

func Test_github.com/ConductorOne/baton-jumpcloud/pkg/jcapi_CloudInsightsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CloudInsightsApiService CloudInsightsCreateAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsCreateAccount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsCreateSavedView", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsCreateSavedView(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsDeleteSavedView", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var viewId string

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsDeleteSavedView(context.Background(), viewId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsFetchDistinctFieldValues", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsFetchDistinctFieldValues(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsFetchSavedView", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var viewId string

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsFetchSavedView(context.Background(), viewId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsFetchSavedViewsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsFetchSavedViewsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsGetAccountByID", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudInsightsId string

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsGetAccountByID(context.Background(), cloudInsightsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsListAccounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsListAccounts(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsListEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsListEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsUpdateAccountByID", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cloudInsightsId string

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsUpdateAccountByID(context.Background(), cloudInsightsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudInsightsApiService CloudInsightsUpdateSavedView", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var viewId string

		resp, httpRes, err := apiClient.CloudInsightsApi.CloudInsightsUpdateSavedView(context.Background(), viewId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
