/*
JumpCloud API

Testing Office365ImportApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jcapi2

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/conductorone/baton-jumpcloud/pkg/jcapi2"
)

func Test_jcapi2_Office365ImportApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test Office365ImportApiService Office365sListImportUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var office365Id string

		resp, httpRes, err := apiClient.Office365ImportApi.Office365sListImportUsers(context.Background(), office365Id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
