/*
JumpCloud API

Testing CustomEmailsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CustomEmailsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CustomEmailsApiService CustomEmailsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomEmailsApi.CustomEmailsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomEmailsApiService CustomEmailsDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customEmailType string

		httpRes, err := apiClient.CustomEmailsApi.CustomEmailsDestroy(context.Background(), customEmailType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomEmailsApiService CustomEmailsGetTemplates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomEmailsApi.CustomEmailsGetTemplates(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomEmailsApiService CustomEmailsRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customEmailType string

		resp, httpRes, err := apiClient.CustomEmailsApi.CustomEmailsRead(context.Background(), customEmailType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomEmailsApiService CustomEmailsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customEmailType string

		resp, httpRes, err := apiClient.CustomEmailsApi.CustomEmailsUpdate(context.Background(), customEmailType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
