/*
JumpCloud API

Testing AdministratorsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_AdministratorsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AdministratorsApiService AdministratorOrganizationsCreateByAdministrator", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.AdministratorsApi.AdministratorOrganizationsCreateByAdministrator(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdministratorsApiService AdministratorOrganizationsListByAdministrator", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.AdministratorsApi.AdministratorOrganizationsListByAdministrator(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdministratorsApiService AdministratorOrganizationsListByOrganization", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.AdministratorsApi.AdministratorOrganizationsListByOrganization(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdministratorsApiService AdministratorOrganizationsRemoveByAdministrator", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var administratorId string
		var id string

		httpRes, err := apiClient.AdministratorsApi.AdministratorOrganizationsRemoveByAdministrator(context.Background(), administratorId, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
